### ISSUE TITLE
Testing the program

### ISSUE THREAD

**Issue by su8** [su8/hackzy#1]
Hello @lasers, can you test this game. It's my first c++ program and game. Got a new laptop, but this game was developed from my tablet initially, after that from my laptop :)

**Comment by lasers** [comment]
Ah sorry. I forget. I got this notification on my phone and went around with my usual stuff. Yeah, I have been using macOS lately and pretty much stopped testing stuff. I have been using NixOS too. I find NixOS pretty cool too. Something you might want to check out if you have time.

I have my backlog games that I want to play too. Not giving you excuses. Just saying that's cool and all, lol.

**Comment by su8** [comment]
It's okay mate.

Just replace **srandom** with **srand**.

https://github.com/su8/hackzy/blob/a69c66e252bd5e9f78ca2f4a6498edd9318e747e/main.cpp#L304

and compile it with `make`. The GUI version requires qt5/qt6 and once installed, open up Qt Creator and press **CTRL** + **r**, or `cmake .` followed by `make -j8`.
